version: "3.9"
services:
  phil-photos-db:
    image: postgres
    restart: always
    container_name: phil-photos-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

  phil-photos-objectstore:
    image: quay.io/minio/minio:latest
    command: minio server --console-address ":9001" /data
    restart: always
    container_name: phil-photos-objectstore
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - miniodata:/data

volumes:
  pgdata:
  miniodata:
